/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier Example](https://github.com/nlpsandbox/phi-deidentifier-example) 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DeidentifyRequest,
    DeidentifyRequestFromJSON,
    DeidentifyRequestToJSON,
    DeidentifyResponse,
    DeidentifyResponseFromJSON,
    DeidentifyResponseToJSON,
} from '../models';

export interface CreateDeidentifiedNotesRequest {
    deidentifyRequest?: DeidentifyRequest;
}

/**
 * 
 */
export class DeidentifiedNoteApi extends runtime.BaseAPI {

    /**
     * Returns the deidentified note
     * Deidentify a clinical note
     */
    async createDeidentifiedNotesRaw(requestParameters: CreateDeidentifiedNotesRequest): Promise<runtime.ApiResponse<DeidentifyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/deidentifiedNotes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeidentifyRequestToJSON(requestParameters.deidentifyRequest),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => DeidentifyResponseFromJSON(jsonValue));
    }

    /**
     * Returns the deidentified note
     * Deidentify a clinical note
     */
    async createDeidentifiedNotes(requestParameters: CreateDeidentifiedNotesRequest): Promise<DeidentifyResponse> {
        const response = await this.createDeidentifiedNotesRaw(requestParameters);
        return await response.value();
    }

}
