/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier) 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TextDateAnnotation,
    TextDateAnnotationFromJSON,
    TextDateAnnotationFromJSONTyped,
    TextDateAnnotationToJSON,
    TextPersonNameAnnotation,
    TextPersonNameAnnotationFromJSON,
    TextPersonNameAnnotationFromJSONTyped,
    TextPersonNameAnnotationToJSON,
    TextPhysicalAddressAnnotation,
    TextPhysicalAddressAnnotationFromJSON,
    TextPhysicalAddressAnnotationFromJSONTyped,
    TextPhysicalAddressAnnotationToJSON,
} from './';

/**
 * Set of annotations of all types for a text
 * @export
 * @interface AnnotationSet
 */
export interface AnnotationSet {
    /**
     * Date annotations in a text
     * @type {Array<TextDateAnnotation>}
     * @memberof AnnotationSet
     */
    textDateAnnotations: Array<TextDateAnnotation>;
    /**
     * Person name annotations in a text
     * @type {Array<TextPersonNameAnnotation>}
     * @memberof AnnotationSet
     */
    textPersonNameAnnotations: Array<TextPersonNameAnnotation>;
    /**
     * Physical address annotations in a text
     * @type {Array<TextPhysicalAddressAnnotation>}
     * @memberof AnnotationSet
     */
    textPhysicalAddressAnnotations: Array<TextPhysicalAddressAnnotation>;
}

export function AnnotationSetFromJSON(json: any): AnnotationSet {
    return AnnotationSetFromJSONTyped(json, false);
}

export function AnnotationSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotationSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'textDateAnnotations': ((json['textDateAnnotations'] as Array<any>).map(TextDateAnnotationFromJSON)),
        'textPersonNameAnnotations': ((json['textPersonNameAnnotations'] as Array<any>).map(TextPersonNameAnnotationFromJSON)),
        'textPhysicalAddressAnnotations': ((json['textPhysicalAddressAnnotations'] as Array<any>).map(TextPhysicalAddressAnnotationFromJSON)),
    };
}

export function AnnotationSetToJSON(value?: AnnotationSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'textDateAnnotations': ((value.textDateAnnotations as Array<any>).map(TextDateAnnotationToJSON)),
        'textPersonNameAnnotations': ((value.textPersonNameAnnotations as Array<any>).map(TextPersonNameAnnotationToJSON)),
        'textPhysicalAddressAnnotations': ((value.textPhysicalAddressAnnotations as Array<any>).map(TextPhysicalAddressAnnotationToJSON)),
    };
}


