/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Configuration for the "date offset" strategy. E.g. "John Smith visited on 1 January 2020" -> "John Smith visited on 29 October 2025". Note, can only be set with the "text_date" annotation type.
 * @export
 * @interface DateOffsetConfig
 */
export interface DateOffsetConfig {
    /**
     * Number of days by which to offset annotated dates.
     * @type {number}
     * @memberof DateOffsetConfig
     */
    offsetDays: number;
}

export function DateOffsetConfigFromJSON(json: any): DateOffsetConfig {
    return DateOffsetConfigFromJSONTyped(json, false);
}

export function DateOffsetConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateOffsetConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offsetDays': json['offsetDays'],
    };
}

export function DateOffsetConfigToJSON(value?: DateOffsetConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offsetDays': value.offsetDays,
    };
}


