/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier Example](https://github.com/nlpsandbox/phi-deidentifier-example) 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeidentificationStep,
    DeidentificationStepFromJSON,
    DeidentificationStepFromJSONTyped,
    DeidentificationStepToJSON,
    Note,
    NoteFromJSON,
    NoteFromJSONTyped,
    NoteToJSON,
} from './';

/**
 * A request to de-identify a clinical note
 * @export
 * @interface DeidentifyRequest
 */
export interface DeidentifyRequest {
    /**
     * 
     * @type {Note}
     * @memberof DeidentifyRequest
     */
    note: Note;
    /**
     * A list of deidentification steps
     * @type {Array<DeidentificationStep>}
     * @memberof DeidentifyRequest
     */
    deidentificationSteps: Array<DeidentificationStep>;
}

export function DeidentifyRequestFromJSON(json: any): DeidentifyRequest {
    return DeidentifyRequestFromJSONTyped(json, false);
}

export function DeidentifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeidentifyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'note': NoteFromJSON(json['note']),
        'deidentificationSteps': ((json['deidentificationSteps'] as Array<any>).map(DeidentificationStepFromJSON)),
    };
}

export function DeidentifyRequestToJSON(value?: DeidentifyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'note': NoteToJSON(value.note),
        'deidentificationSteps': ((value.deidentificationSteps as Array<any>).map(DeidentificationStepToJSON)),
    };
}


