/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents the health of a service
 * @export
 * @interface HealthCheck
 */
export interface HealthCheck {
    /**
     * Indicates whether the service status is acceptable or not
     * @type {string}
     * @memberof HealthCheck
     */
    status: HealthCheckStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum HealthCheckStatusEnum {
    Pass = 'pass',
    Fail = 'fail',
    Warn = 'warn'
}

export function HealthCheckFromJSON(json: any): HealthCheck {
    return HealthCheckFromJSONTyped(json, false);
}

export function HealthCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthCheckToJSON(value?: HealthCheck | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}


