/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Problem details (tools.ietf.org/html/rfc7807)
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * A human readable documentation for the problem type
     * @type {string}
     * @memberof ModelError
     */
    title: string;
    /**
     * The HTTP status code
     * @type {number}
     * @memberof ModelError
     */
    status: number;
    /**
     * A human readable explanation specific to this occurrence of the problem
     * @type {string}
     * @memberof ModelError
     */
    detail?: string;
    /**
     * An absolute URI that identifies the problem type
     * @type {string}
     * @memberof ModelError
     */
    type?: string;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'status': json['status'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'status': value.status,
        'detail': value.detail,
        'type': value.type,
    };
}


