/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier) 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A clinical note
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * The ID of the clinical note
     * @type {string}
     * @memberof Note
     */
    identifier: string;
    /**
     * The content of the clinical note
     * @type {string}
     * @memberof Note
     */
    text: string;
    /**
     * The note type (LOINC concept)
     * @type {string}
     * @memberof Note
     */
    noteType: string;
    /**
     * The ID of the FHIR patient
     * @type {string}
     * @memberof Note
     */
    patientId: string;
}

export function NoteFromJSON(json: any): Note {
    return NoteFromJSONTyped(json, false);
}

export function NoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Note {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'text': json['text'],
        'noteType': json['noteType'],
        'patientId': json['patientId'],
    };
}

export function NoteToJSON(value?: Note | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'text': value.text,
        'noteType': value.noteType,
        'patientId': value.patientId,
    };
}


