/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier Example](https://github.com/nlpsandbox/phi-deidentifier-example) 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TextAnnotation,
    TextAnnotationFromJSON,
    TextAnnotationFromJSONTyped,
    TextAnnotationToJSON,
    TextLocationAnnotationAllOf,
    TextLocationAnnotationAllOfFromJSON,
    TextLocationAnnotationAllOfFromJSONTyped,
    TextLocationAnnotationAllOfToJSON,
} from './';

/**
 * A location annotation in a text
 * @export
 * @interface TextLocationAnnotation
 */
export interface TextLocationAnnotation {
    /**
     * The position of the first character
     * @type {number}
     * @memberof TextLocationAnnotation
     */
    start: number;
    /**
     * The length of the annotation
     * @type {number}
     * @memberof TextLocationAnnotation
     */
    length: number;
    /**
     * The string annotated
     * @type {string}
     * @memberof TextLocationAnnotation
     */
    text: string;
    /**
     * The confidence in the accuracy of the annotation
     * @type {number}
     * @memberof TextLocationAnnotation
     */
    confidence: number;
    /**
     * Type of location
     * @type {string}
     * @memberof TextLocationAnnotation
     */
    locationType: TextLocationAnnotationLocationTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum TextLocationAnnotationLocationTypeEnum {
    City = 'city',
    Country = 'country',
    Department = 'department',
    Hospital = 'hospital',
    Organization = 'organization',
    Other = 'other',
    Room = 'room',
    State = 'state',
    Street = 'street',
    Zip = 'zip'
}

export function TextLocationAnnotationFromJSON(json: any): TextLocationAnnotation {
    return TextLocationAnnotationFromJSONTyped(json, false);
}

export function TextLocationAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextLocationAnnotation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'length': json['length'],
        'text': json['text'],
        'confidence': json['confidence'],
        'locationType': json['locationType'],
    };
}

export function TextLocationAnnotationToJSON(value?: TextLocationAnnotation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'length': value.length,
        'text': value.text,
        'confidence': value.confidence,
        'locationType': value.locationType,
    };
}


