/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier Example](https://github.com/nlpsandbox/phi-deidentifier-example) 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextLocationAnnotationAllOf
 */
export interface TextLocationAnnotationAllOf {
    /**
     * Type of location
     * @type {string}
     * @memberof TextLocationAnnotationAllOf
     */
    locationType: TextLocationAnnotationAllOfLocationTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum TextLocationAnnotationAllOfLocationTypeEnum {
    City = 'city',
    Country = 'country',
    Department = 'department',
    Hospital = 'hospital',
    Organization = 'organization',
    Other = 'other',
    Room = 'room',
    State = 'state',
    Street = 'street',
    Zip = 'zip'
}

export function TextLocationAnnotationAllOfFromJSON(json: any): TextLocationAnnotationAllOf {
    return TextLocationAnnotationAllOfFromJSONTyped(json, false);
}

export function TextLocationAnnotationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextLocationAnnotationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locationType': json['locationType'],
    };
}

export function TextLocationAnnotationAllOfToJSON(value?: TextLocationAnnotationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locationType': value.locationType,
    };
}


