/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Overview This NLP tool relies on the following NLP tools to deidentify a clinical note given as input. - Data Annotator - Person Name Annotator - Physical Address Annotator - TBA 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TextAnnotation,
    TextAnnotationFromJSON,
    TextAnnotationFromJSONTyped,
    TextAnnotationToJSON,
} from './';

/**
 * A person name annotation in a text
 * @export
 * @interface TextPersonNameAnnotation
 */
export interface TextPersonNameAnnotation {
    /**
     * The position of the first character
     * @type {number}
     * @memberof TextPersonNameAnnotation
     */
    start: number;
    /**
     * The length of the annotation
     * @type {number}
     * @memberof TextPersonNameAnnotation
     */
    length: number;
    /**
     * The string annotated
     * @type {string}
     * @memberof TextPersonNameAnnotation
     */
    text: string;
    /**
     * The confidence in the accuracy of the annotation
     * @type {number}
     * @memberof TextPersonNameAnnotation
     */
    confidence?: number;
}

export function TextPersonNameAnnotationFromJSON(json: any): TextPersonNameAnnotation {
    return TextPersonNameAnnotationFromJSONTyped(json, false);
}

export function TextPersonNameAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextPersonNameAnnotation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'length': json['length'],
        'text': json['text'],
        'confidence': !exists(json, 'confidence') ? undefined : json['confidence'],
    };
}

export function TextPersonNameAnnotationToJSON(value?: TextPersonNameAnnotation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'length': value.length,
        'text': value.text,
        'confidence': value.confidence,
    };
}


