/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier Example](https://github.com/nlpsandbox/phi-deidentifier-example) 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An annotation in a text
 * @export
 * @interface TextAnnotation
 */
export interface TextAnnotation {
    /**
     * The position of the first character
     * @type {number}
     * @memberof TextAnnotation
     */
    start: number;
    /**
     * The length of the annotation
     * @type {number}
     * @memberof TextAnnotation
     */
    length: number;
    /**
     * The string annotated
     * @type {string}
     * @memberof TextAnnotation
     */
    text: string;
    /**
     * The confidence in the accuracy of the annotation
     * @type {number}
     * @memberof TextAnnotation
     */
    confidence: number;
}

export function TextAnnotationFromJSON(json: any): TextAnnotation {
    return TextAnnotationFromJSONTyped(json, false);
}

export function TextAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextAnnotation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'length': json['length'],
        'text': json['text'],
        'confidence': json['confidence'],
    };
}

export function TextAnnotationToJSON(value?: TextAnnotation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'length': value.length,
        'text': value.text,
        'confidence': value.confidence,
    };
}


