/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier](https://github.com/nlpsandbox/phi-deidentifier) 
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TextAnnotation,
    TextAnnotationFromJSON,
    TextAnnotationFromJSONTyped,
    TextAnnotationToJSON,
    TextContactAnnotationAllOf,
    TextContactAnnotationAllOfFromJSON,
    TextContactAnnotationAllOfFromJSONTyped,
    TextContactAnnotationAllOfToJSON,
} from './';

/**
 * A contact annotation in a text
 * @export
 * @interface TextContactAnnotation
 */
export interface TextContactAnnotation {
    /**
     * The position of the first character
     * @type {number}
     * @memberof TextContactAnnotation
     */
    start: number;
    /**
     * The length of the annotation
     * @type {number}
     * @memberof TextContactAnnotation
     */
    length: number;
    /**
     * The string annotated
     * @type {string}
     * @memberof TextContactAnnotation
     */
    text: string;
    /**
     * The confidence in the accuracy of the annotation
     * @type {number}
     * @memberof TextContactAnnotation
     */
    confidence: number;
    /**
     * Type of contact information
     * @type {string}
     * @memberof TextContactAnnotation
     */
    contactType: TextContactAnnotationContactTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum TextContactAnnotationContactTypeEnum {
    Email = 'email',
    Fax = 'fax',
    IpAddress = 'ip_address',
    Phone = 'phone',
    Url = 'url',
    Other = 'other'
}

export function TextContactAnnotationFromJSON(json: any): TextContactAnnotation {
    return TextContactAnnotationFromJSONTyped(json, false);
}

export function TextContactAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextContactAnnotation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': json['start'],
        'length': json['length'],
        'text': json['text'],
        'confidence': json['confidence'],
        'contactType': json['contactType'],
    };
}

export function TextContactAnnotationToJSON(value?: TextContactAnnotation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start,
        'length': value.length,
        'text': value.text,
        'confidence': value.confidence,
        'contactType': value.contactType,
    };
}


