/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Introduction This NLP tool takes as input a clinical note and returned a de-identified version of the note. This design of this API is a work in progress. # Examples - [NLP Sandbox PHI Deidentifier Example](https://github.com/nlpsandbox/phi-deidentifier-example) 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: team@nlpsandbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of this tool
 * @export
 * @enum {string}
 */
export enum ToolType {
    ContactAnnotator = 'nlpsandbox:contact-annotator',
    CovidSymptomAnnotator = 'nlpsandbox:covid-symptom-annotator',
    DataNode = 'nlpsandbox:data-node',
    DateAnnotator = 'nlpsandbox:date-annotator',
    IdAnnotator = 'nlpsandbox:id-annotator',
    LocationAnnotator = 'nlpsandbox:location-annotator',
    PersonNameAnnotator = 'nlpsandbox:person-name-annotator',
    PhiAnnotator = 'nlpsandbox:phi-annotator',
    PhiDeidentifier = 'nlpsandbox:phi-deidentifier'
}

export function ToolTypeFromJSON(json: any): ToolType {
    return ToolTypeFromJSONTyped(json, false);
}

export function ToolTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolType {
    return json as ToolType;
}

export function ToolTypeToJSON(value?: ToolType | null): any {
    return value as any;
}

