/* tslint:disable */
/* eslint-disable */
/**
 * NLP Sandbox PHI Deidentifier API
 * # Overview This NLP tool relies on the following NLP tools to deidentify a clinical note given as input. - Data Annotator - Person Name Annotator - Physical Address Annotator - TBA 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    License,
    LicenseFromJSON,
    LicenseFromJSONTyped,
    LicenseToJSON,
} from './';

/**
 * Information about an NLP tool
 * @export
 * @interface Tool
 */
export interface Tool {
    /**
     * The tool name
     * @type {string}
     * @memberof Tool
     */
    name: string;
    /**
     * The version of the tool (SemVer string)
     * @type {string}
     * @memberof Tool
     */
    version: string;
    /**
     * 
     * @type {License}
     * @memberof Tool
     */
    license: License;
    /**
     * The place where the code lives
     * @type {string}
     * @memberof Tool
     */
    repository: string;
    /**
     * A short, one-sentence summary of the tool
     * @type {string}
     * @memberof Tool
     */
    description: string;
    /**
     * The author of the tool
     * @type {string}
     * @memberof Tool
     */
    author: string;
    /**
     * The email address of the author
     * @type {string}
     * @memberof Tool
     */
    authorEmail: string;
    /**
     * The URL to the homepage of the tool
     * @type {string}
     * @memberof Tool
     */
    url: string;
    /**
     * The type of this tool
     * @type {string}
     * @memberof Tool
     */
    toolType: string;
    /**
     * The version of the tool OpenAPI specification
     * @type {string}
     * @memberof Tool
     */
    toolApiVersion: string;
}

export function ToolFromJSON(json: any): Tool {
    return ToolFromJSONTyped(json, false);
}

export function ToolFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tool {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
        'license': LicenseFromJSON(json['license']),
        'repository': json['repository'],
        'description': json['description'],
        'author': json['author'],
        'authorEmail': json['authorEmail'],
        'url': json['url'],
        'toolType': json['toolType'],
        'toolApiVersion': json['toolApiVersion'],
    };
}

export function ToolToJSON(value?: Tool | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'version': value.version,
        'license': LicenseToJSON(value.license),
        'repository': value.repository,
        'description': value.description,
        'author': value.author,
        'authorEmail': value.authorEmail,
        'url': value.url,
        'toolType': value.toolType,
        'toolApiVersion': value.toolApiVersion,
    };
}


